# 4 - Numerical computing with Numpy

__NumPy__ library: two data structures within the library are:
- `ndarray(regular)`: n-dimensional array object
- `ndarray(record)`: 2-dimensional array object (tabular data)

### Nesting lists
Nesting python lists works with reference pointers to the original objects, for example:

In [2]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [3]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [5]:
# This can be avoided using the deepcopy() function
from copy import deepcopy
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = 3 * [deepcopy(v), ]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

### Array class
Defines an object type which can compactly represent an array of basic values. They behave like lists except that the type of objects stored in them is constrained. 

__A key advantage of the array class is that it has built in storage and retrieval__

In [6]:
import array
a = array.array('f', v)

In [7]:
a.append(0.5)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [9]:
a.extend([5.0, 6.75])
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [10]:
2*a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [11]:
a.append('string')

TypeError: a float is required

In [19]:
# Built in file storage and retrieval
with open('array.apy', 'wb') as f: # opens a file on disk for writing a binary file
    a.tofile(f) # writes the array data to the file
#f.close() # closes the file but you don't need it when using a with context

%ls -n arr*

 Volume in drive C is OSDisk
 Volume Serial Number is 844B-B07F

 Directory of C:\Windows\System32


 Directory of C:\Windows\System32



File Not Found


### NumPy arrays
A truly specialised class to handle array-type structures. Built to handle arrays in a highly performant manner.

In [22]:
import numpy as np

a = np.array([0.0, 0.5, 1.0, 1.5, 2.0])
type(a)

numpy.ndarray

In [23]:
a = np.array(['a', 'b', 'c'])
a

array(['a', 'b', 'c'], 
      dtype='<U1')

In [25]:
a = np.arange(2, 20, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
a = np.arange(8, dtype=np.float)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.])

There is a multitude of built in functions (including vectorized mathematical operations)

In [27]:
a.sum()

28.0

In [28]:
a.std()

2.2912878474779199

In [29]:
a.cumsum()

array([  0.,   1.,   3.,   6.,  10.,  15.,  21.,  28.])

In [30]:
# Scalar multiplication of a list results in duplication of the elements
l = [0., 0.5, 1.5, 3., 5.]
2 * l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [31]:
# whereas scalar multiplication in numpy leads to proper scalar multiplication
2 * a

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.])

In [32]:
# element-wise square values
a ** 2

array([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.])

In [33]:
# 2 raised to the power of each element value
2 ** a

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.])

In [38]:
# Universal functions in the sense that they operate on ordinary python
# objects as well as numpy arrays, but they do have a performance cost
# compared to the math functions
import math

math.sqrt(a) # cannot use conventional math functions on numpy arrays


TypeError: only length-1 arrays can be converted to Python scalars

In [37]:
%timeit np.sqrt(2.5)

The slowest run took 20.89 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.05 µs per loop


In [36]:
%timeit math.sqrt(2.5)

The slowest run took 6.87 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 265 ns per loop


In [41]:
# Multiple dimensions:
# The indexing system is made consistent across all dimensions
b = np.array([a, a * 2])
b

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.],
       [  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.]])

In [42]:
b[0]

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.])

In [43]:
b[0, 2]

2.0

In [44]:
b[:, 1]

array([ 1.,  2.])

In [45]:
b.sum(axis=0)

array([  0.,   3.,   6.,   9.,  12.,  15.,  18.,  21.])

In [46]:
b.sum(axis=1)

array([ 28.,  56.])

In [48]:
# One can instantiate the array to contain all zeros, to be populated later
c = np.zeros((2, 3), dtype='i', order='C') # order in which to store columns in memory (C like in C++)
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [49]:
c = np.ones((2, 3, 4), dtype='i', order='C')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [53]:
d = np.zeros_like(c, dtype='longdouble', order='C')
d

array([[[ 0.0,  0.0,  0.0,  0.0],
        [ 0.0,  0.0,  0.0,  0.0],
        [ 0.0,  0.0,  0.0,  0.0]],

       [[ 0.0,  0.0,  0.0,  0.0],
        [ 0.0,  0.0,  0.0,  0.0],
        [ 0.0,  0.0,  0.0,  0.0]]], dtype=float64)

ndarray class is superior to the list based approach:
- ndarray object has built in dimensions (axes)
- ndarray is immutable; its length (size) is fixed
- it only allows for a single data type (np.dtype) for the whole array

It is immutable by default, but there are options to reshape and resize. Reshape just provides another view on the same data, whereas resize creates a new temporary object.

In [4]:
g = np.arange(15)
np.shape(g)

(15,)

In [5]:
g.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
g.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
g.transpose()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
h = g.reshape(5, 3)
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

__Boolean arrays__

In [14]:
h <= 7 # such boolean arrays can be used for indexing and data selection

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]], dtype=bool)

In [15]:
h[h > 8] # notice that the data are flattened

array([ 9, 10, 11, 12, 13, 14])

In [16]:
np.where(h > 7, 1, 0) # the np.where function preserves the original shape

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
np.where(h % 2 == 0, 'even', 'odd') # instead of 1 & 0 as defined in the previous example

array([['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even']], 
      dtype='<U4')

__Simple example: pure Python approach__

The generation of a matrix with shape 5,000 x 5,000 elements, populated with pseudo-random, standard normally distributed numbers. Then compute the sum of all elements.

In [20]:
import random
I = 5000

%time mat = [[random.gauss(0, 1) for j in range(I)] \
             for i in range(I)]

Wall time: 35.2 s


In [21]:
mat[0][:5]

[1.0833378278477301,
 -0.9810201233799811,
 1.7263648966650629,
 -0.30650945172498784,
 0.7260758737491618]

In [22]:
%time sum([sum(l) for l in mat])

Wall time: 156 ms


-8845.066769894951

In [25]:
import sys
sum([sys.getsizeof(l) for l in mat]) # adds up the memory usage of all elements

215200000

__Simple example: NumPy approach__

In [26]:
%time mat = np.random.standard_normal((I, I)) # about 14 times faster

Wall time: 1.81 s


In [35]:
%time mat.sum()

Wall time: 35.9 ms


-5239.3845045695762

In [31]:
mat.nbytes

200000000

In [29]:
sys.getsizeof(mat) # saves some memory overhead

200000112

__Structured NumPy arrays__

NumPy provides structured `ndarray` and record `recarry` that allow you to have a different `dtype` per column.

Structured arrays are a generalization of the regular `ndarray` object type in that the data type has to be the same per column (like in SQL databases). One advantage of structured arrays is that a single element of a column can be another multidimensional object and does not have to conform to the basic NumPy data types.

In [36]:
dt = np.dtype([('Name', 'S10'),
               ('Age', 'i4'),
               ('Height', 'f'),
               ('Children/Pets', 'i4', 2)])
dt

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [39]:
s = np.array([('Smith', 45, 1.83, (0, 1)),
              ('Jones', 53, 1.72, (2, 2))], dtype=dt)
s

array([(b'Smith', 45, 1.8300000429153442, [0, 1]),
       (b'Jones', 53, 1.7200000286102295, [2, 2])], 
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [40]:
s['Name']

array([b'Smith', b'Jones'], 
      dtype='|S10')

In [41]:
s['Height'].mean()

1.7750001

In [42]:
s[0]

(b'Smith', 45, 1.8300000429153442, [0, 1])

__Vectorisation of code__

It is a strategy to get more compact code that is possibly executed faster. Fundamental idea is to conduct an operation on or to apply a function to a complex object 'at once' and not by looping over the single elements of the object.

Functional programming tools such as `map()` and `filter()` provide some basic means for vectorisation. However, NumPy has it built in.

Functions work with ndarray objects, resulting in a vectorised evaluation of the function. NumPy applies the function to the object element-wise. 

__Loops are not on the Python level but they are on the NumPy level. This is taken care of by optimised code, mostly written in C and therefore generally faster than pure Python.__

In [44]:
np.random.seed(100)
r = np.arange(12).reshape((4, 3))
s = np.arange(12).reshape((4, 3)) * 0.5
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [45]:
r + s # element-wise addition as a vectorised operation (no looping)

array([[  0. ,   1.5,   3. ],
       [  4.5,   6. ,   7.5],
       [  9. ,  10.5,  12. ],
       [ 13.5,  15. ,  16.5]])

In [46]:
def f(x):
    return 3 * x + 5
f(0.5)

6.5

In [49]:
f(r) 

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

__Memory layout__

When `ndarray` objects are initialised, an optional argument for the memory layout is provided. This argument specifies (approximately) which elements of an array get stored in memory next to each other. 

When arrays get large, then this may have a material impact.

In [50]:
x = np.random.standard_normal((1000000, 5))
y = 2 * x + 3
C = np.array((x, y), order='C') # row-major
F = np.array((x, y), order='F') # column-major
x = 0.0; y = 0.0 # memory is freed up contingent on garbage collection
C[:2].round(2)

array([[[-1.75,  0.34,  1.15, -0.25,  0.98],
        [ 0.51,  0.22, -1.07, -0.19,  0.26],
        [-0.46,  0.44, -0.58,  0.82,  0.67],
        ..., 
        [-0.05,  0.14,  0.17,  0.33,  1.39],
        [ 1.02,  0.3 , -1.23, -0.68, -0.87],
        [ 0.83, -0.73,  1.03,  0.34, -0.46]],

       [[-0.5 ,  3.69,  5.31,  2.5 ,  4.96],
        [ 4.03,  3.44,  0.86,  2.62,  3.51],
        [ 2.08,  3.87,  1.83,  4.63,  4.35],
        ..., 
        [ 2.9 ,  3.28,  3.33,  3.67,  5.78],
        [ 5.04,  3.6 ,  0.54,  1.65,  1.26],
        [ 4.67,  1.54,  5.06,  3.69,  2.07]]])

In [51]:
%timeit C.sum()

100 loops, best of 3: 20.4 ms per loop


In [52]:
%timeit F.sum()

100 loops, best of 3: 20.4 ms per loop


In [53]:
%timeit C.sum(axis=0)

10 loops, best of 3: 50.3 ms per loop


In [59]:
%timeit C.sum(axis=1)

10 loops, best of 3: 83.4 ms per loop


In [60]:
%timeit F.sum(axis=0)

10 loops, best of 3: 222 ms per loop


In [61]:
%timeit F.sum(axis=1)

10 loops, best of 3: 181 ms per loop


In [62]:
F = 0.0; C = 0.0